/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Fallback: typeof import('./components/fallback/fallback.vue')['default']
    Icon403: typeof import('./components/fallback/icons/icon-403.vue')['default']
    Icon404: typeof import('./components/fallback/icons/icon-404.vue')['default']
    Icon500: typeof import('./components/fallback/icons/icon-500.vue')['default']
    IconComingSoon: typeof import('./components/fallback/icons/icon-coming-soon.vue')['default']
    IconOffline: typeof import('./components/fallback/icons/icon-offline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
